spring:
  profiles: 
    active: dev
  application: 
    name: evouchers
  thymeleaf:
    prefix: classpath:/templates/mail/
#  mvc: 
#    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
    
### specific app properties
mail: 
  from: 
  answer: 
  archive: 
  
voucher:  
  responsible: 
barcode: 
  key: 

---
### dev profil

spring:
  profiles: dev
### data access
  datasource:
    driver-class-name: org.postgresql.Driver
    username: 
    password: 
    url: jdbc:postgresql://localhost:5432/evouchersdb

  jooq:
    sql-dialect: POSTGRES
    
    
### mail
  mail: 
    default-encoding: UTF-8
    host: smtp.gmail.com
    protocol: smtp
    port: 587
    username: 
    password: 
    test-connection: false
    properties: 
      mail: 
        smtp: 
          auth: true
          starttls: 
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

          

server: 
  port: 8443
  ssl:
    key-store: src/main/resources/security/keystore.p12
    key-store-password: password
    keyStoreType: PKCS12
    keyAlias: evouchers
   
### logging
logging: 
  level: 
    org.jooq.tools: DEBUG
    org.bspv.evoucher: DEBUG
    org.springframework.web.servlet.mvc: DEBUG

### security
security: 
  jwt: 
    secret: 
    default-expiration-time: 864000



  